11 set up continuous integration pipeline
mknaranja/GMGPolar pull request #12
Opened 2023-03-15 15:50 UTC by CodingAllan

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
Always to be checked:
* [ ] There is at least one issue associated with the pull request.
* [ ] New code adheres with the [coding guidelines](https://github.com/mknaranja/GMGPolar/wiki)
* [ ] No large data files have been added to the repository. Maximum size for files should be of the order of KB not MB. In particular avoid adding of pdf, word, or other files that cannot be change-tracked correctly by git.

If functions were changed or functionality was added:
* [ ] Tests for new functionality has been added
* [ ] A local test was succesful

If new functionality was added:
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)

If new third party software is used:
* [ ] Did you pay attention to its license? Please remember to add it to the wiki after successful merging.

If new mathematical methods or epidemiological terms are used:
* [ ] Are new methods referenced? Did you provide further documentation?

[ ] The following questions are addressed in the documentation (if need be): 
* Developers (what did you do?, how can it be maintained?)
* For users (how to use your work?)
* For admins (how to install and configure your work?)

* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request. All reviewers should squash commits and write a simple and meaningful commit message.
* [ ] Coverage report for new code is acceptable. 
* [ ] No large data files have been added to the repository. Maximum size for files should be of the order of KB not MB. In particular avoid adding of pdf, word, or other files that cannot be change-tracked correctly by git.

2023-03-15 16:04 UTC, CodingAllan commented on .github/actions/build/action.yml
I have oriented myself to memilio and how the CI is implemented there.
 I am not sure if it is the best practise to upload the build as a archive and to download it immediately in the test.

I had to delete it after the test concluded, since it lead to an Error on subsequent pushes to the repository. These error vanished after i deleted the archive and re-run the test!

2023-03-23 15:05 UTC, mknaranja requested changes
Thank you for setting up the CI @CodingAllan . I have made some minor comments.

2023-03-23 15:05 UTC, mknaranja commented on .github/workflows/main.yml
> +on : [push]
```suggestion
on :
  schedule:
    - cron: "40 2 * * *"
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
```

I would like to have the CI to be run only on pushes on pull requests and on a nightly cron job build.

2023-03-23 15:05 UTC, mknaranja commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
```suggestion
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
```

2023-03-23 15:05 UTC, mknaranja commented on .github/actions/build/action.yml
> +name: "Build Repository on Linux"
```suggestion
name: "Linux Build"
```

2023-03-23 15:05 UTC, mknaranja commented on .github/actions/build/action.yml
> +      #guarantee that the latest compiler version is used
```suggestion
      # ensure that the installed compiler version is used
```

2023-03-23 15:05 UTC, mknaranja commented on .github/actions/build/action.yml
> +        make
```suggestion
        make -j4
```
Make in parallel

2023-03-23 15:05 UTC, mknaranja commented on .github/workflows/main.yml
> +  run-unit-test:
```suggestion

  run-unit-test:
```

2023-03-23 15:05 UTC, mknaranja commented on .github/actions/test/action.yml
> +        retention-days:
```suggestion
        retention-days: 3
```

2023-03-23 15:05 UTC, mknaranja commented on .github/actions/test/action.yml
> +        name: ${{ inputs.build-artifact }}
```suggestion
    - name: clean-up
      uses: geekyeggo/delete-artifact@v1
      with:
        name: ${{ inputs.build-artifact }} 
```

I think if we do not clean up, we can retain it and download it for some days here for example: https://github.com/mknaranja/GMGPolar/actions/runs/4434953337?pr=12

2023-03-23 17:28 UTC, merged